// Mocks generated by Mockito 5.4.4 from annotations
// in cinema_club/test/features/setting/data/repositories/setting_respoitory_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cinema_club/features/setting/data/datasources/setting_local_data_source.dart'
    as _i3;
import 'package:cinema_club/features/setting/data/models/setting_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSettingModel_0 extends _i1.SmartFake implements _i2.SettingModel {
  _FakeSettingModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SettingLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingLocalDataSource extends _i1.Mock
    implements _i3.SettingLocalDataSource {
  @override
  _i4.Future<_i2.SettingModel> getSetting() => (super.noSuchMethod(
        Invocation.method(
          #getSetting,
          [],
        ),
        returnValue: _i4.Future<_i2.SettingModel>.value(_FakeSettingModel_0(
          this,
          Invocation.method(
            #getSetting,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.SettingModel>.value(_FakeSettingModel_0(
          this,
          Invocation.method(
            #getSetting,
            [],
          ),
        )),
      ) as _i4.Future<_i2.SettingModel>);

  @override
  _i4.Future<void> saveSetting(_i2.SettingModel? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSetting,
          [settings],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
