// Mocks generated by Mockito 5.4.4 from annotations
// in cinema_club/test/features/add_movie_favorite/presentation/bloc/movie_favorite_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cinema_club/core/errors/failures.dart' as _i6;
import 'package:cinema_club/features/add_movie_favorite/data/models/movie_favorite_model.dart'
    as _i7;
import 'package:cinema_club/features/add_movie_favorite/domain/repositories/movie_favorite_repository.dart'
    as _i2;
import 'package:cinema_club/features/add_movie_favorite/domain/usecases/add_movie_to_favorite.dart'
    as _i9;
import 'package:cinema_club/features/add_movie_favorite/domain/usecases/add_remote_movie_to_favorite.dart'
    as _i11;
import 'package:cinema_club/features/add_movie_favorite/domain/usecases/delete_all.dart'
    as _i14;
import 'package:cinema_club/features/add_movie_favorite/domain/usecases/delete_movie_from_favorite.dart'
    as _i8;
import 'package:cinema_club/features/add_movie_favorite/domain/usecases/delete_remote_movie_to_favoirte.dart'
    as _i13;
import 'package:cinema_club/features/add_movie_favorite/domain/usecases/get_favorite_movies.dart'
    as _i4;
import 'package:cinema_club/features/add_movie_favorite/domain/usecases/get_remote_favorite_movies.dart'
    as _i12;
import 'package:cinema_club/features/moviedetails/domain/entities/movie_details_Entity.dart'
    as _i10;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMovieFavoriteRepository_0 extends _i1.SmartFake
    implements _i2.MovieFavoriteRepository {
  _FakeMovieFavoriteRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetFavoriteMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFavoriteMovies extends _i1.Mock implements _i4.GetFavoriteMovies {
  @override
  _i2.MovieFavoriteRepository get repoistories => (super.noSuchMethod(
        Invocation.getter(#repoistories),
        returnValue: _FakeMovieFavoriteRepository_0(
          this,
          Invocation.getter(#repoistories),
        ),
        returnValueForMissingStub: _FakeMovieFavoriteRepository_0(
          this,
          Invocation.getter(#repoistories),
        ),
      ) as _i2.MovieFavoriteRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failures, List<_i7.MovieFavoriteModel>>>
      getFavoriteMovies() => (super.noSuchMethod(
            Invocation.method(
              #getFavoriteMovies,
              [],
            ),
            returnValue: _i5.Future<
                    _i3
                    .Either<_i6.Failures, List<_i7.MovieFavoriteModel>>>.value(
                _FakeEither_1<_i6.Failures, List<_i7.MovieFavoriteModel>>(
              this,
              Invocation.method(
                #getFavoriteMovies,
                [],
              ),
            )),
            returnValueForMissingStub: _i5.Future<
                    _i3
                    .Either<_i6.Failures, List<_i7.MovieFavoriteModel>>>.value(
                _FakeEither_1<_i6.Failures, List<_i7.MovieFavoriteModel>>(
              this,
              Invocation.method(
                #getFavoriteMovies,
                [],
              ),
            )),
          ) as _i5
              .Future<_i3.Either<_i6.Failures, List<_i7.MovieFavoriteModel>>>);
}

/// A class which mocks [DeleteMovieFromFavorite].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteMovieFromFavorite extends _i1.Mock
    implements _i8.DeleteMovieFromFavorite {
  @override
  _i2.MovieFavoriteRepository get repoistories => (super.noSuchMethod(
        Invocation.getter(#repoistories),
        returnValue: _FakeMovieFavoriteRepository_0(
          this,
          Invocation.getter(#repoistories),
        ),
        returnValueForMissingStub: _FakeMovieFavoriteRepository_0(
          this,
          Invocation.getter(#repoistories),
        ),
      ) as _i2.MovieFavoriteRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failures, void>> deleteMovieFromFavorite(
          int? movieId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMovieFromFavorite,
          [movieId],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failures, void>>.value(
            _FakeEither_1<_i6.Failures, void>(
          this,
          Invocation.method(
            #deleteMovieFromFavorite,
            [movieId],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failures, void>>.value(
                _FakeEither_1<_i6.Failures, void>(
          this,
          Invocation.method(
            #deleteMovieFromFavorite,
            [movieId],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failures, void>>);
}

/// A class which mocks [AddMovieToFavorite].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddMovieToFavorite extends _i1.Mock
    implements _i9.AddMovieToFavorite {
  @override
  _i2.MovieFavoriteRepository get repoistories => (super.noSuchMethod(
        Invocation.getter(#repoistories),
        returnValue: _FakeMovieFavoriteRepository_0(
          this,
          Invocation.getter(#repoistories),
        ),
        returnValueForMissingStub: _FakeMovieFavoriteRepository_0(
          this,
          Invocation.getter(#repoistories),
        ),
      ) as _i2.MovieFavoriteRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failures, void>> addMovieToFavorite(
          _i10.MovieDetailsEntity? moive) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMovieToFavorite,
          [moive],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failures, void>>.value(
            _FakeEither_1<_i6.Failures, void>(
          this,
          Invocation.method(
            #addMovieToFavorite,
            [moive],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failures, void>>.value(
                _FakeEither_1<_i6.Failures, void>(
          this,
          Invocation.method(
            #addMovieToFavorite,
            [moive],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failures, void>>);
}

/// A class which mocks [AddRemoteMovieToFavorite].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddRemoteMovieToFavorite extends _i1.Mock
    implements _i11.AddRemoteMovieToFavorite {
  @override
  _i2.MovieFavoriteRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMovieFavoriteRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeMovieFavoriteRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MovieFavoriteRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failures, void>> addRemoteMovieToFavorite(
          _i10.MovieDetailsEntity? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRemoteMovieToFavorite,
          [movie],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failures, void>>.value(
            _FakeEither_1<_i6.Failures, void>(
          this,
          Invocation.method(
            #addRemoteMovieToFavorite,
            [movie],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failures, void>>.value(
                _FakeEither_1<_i6.Failures, void>(
          this,
          Invocation.method(
            #addRemoteMovieToFavorite,
            [movie],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failures, void>>);
}

/// A class which mocks [GetRemoteFavoriteMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRemoteFavoriteMovies extends _i1.Mock
    implements _i12.GetRemoteFavoriteMovies {
  @override
  _i2.MovieFavoriteRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMovieFavoriteRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeMovieFavoriteRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MovieFavoriteRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failures, List<_i7.MovieFavoriteModel>>>
      getRemoteFavoriteMovies() => (super.noSuchMethod(
            Invocation.method(
              #getRemoteFavoriteMovies,
              [],
            ),
            returnValue: _i5.Future<
                    _i3
                    .Either<_i6.Failures, List<_i7.MovieFavoriteModel>>>.value(
                _FakeEither_1<_i6.Failures, List<_i7.MovieFavoriteModel>>(
              this,
              Invocation.method(
                #getRemoteFavoriteMovies,
                [],
              ),
            )),
            returnValueForMissingStub: _i5.Future<
                    _i3
                    .Either<_i6.Failures, List<_i7.MovieFavoriteModel>>>.value(
                _FakeEither_1<_i6.Failures, List<_i7.MovieFavoriteModel>>(
              this,
              Invocation.method(
                #getRemoteFavoriteMovies,
                [],
              ),
            )),
          ) as _i5
              .Future<_i3.Either<_i6.Failures, List<_i7.MovieFavoriteModel>>>);
}

/// A class which mocks [DeleteRemoteMovieToFavoirte].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteRemoteMovieToFavoirte extends _i1.Mock
    implements _i13.DeleteRemoteMovieToFavoirte {
  @override
  _i2.MovieFavoriteRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMovieFavoriteRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeMovieFavoriteRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MovieFavoriteRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failures, void>> deleteRemoteMovieFromFavorite(
          int? movieId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRemoteMovieFromFavorite,
          [movieId],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failures, void>>.value(
            _FakeEither_1<_i6.Failures, void>(
          this,
          Invocation.method(
            #deleteRemoteMovieFromFavorite,
            [movieId],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failures, void>>.value(
                _FakeEither_1<_i6.Failures, void>(
          this,
          Invocation.method(
            #deleteRemoteMovieFromFavorite,
            [movieId],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failures, void>>);
}

/// A class which mocks [DeleteAll].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteAll extends _i1.Mock implements _i14.DeleteAll {
  @override
  _i2.MovieFavoriteRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMovieFavoriteRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeMovieFavoriteRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MovieFavoriteRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failures, void>> deleteAll() => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failures, void>>.value(
            _FakeEither_1<_i6.Failures, void>(
          this,
          Invocation.method(
            #deleteAll,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failures, void>>.value(
                _FakeEither_1<_i6.Failures, void>(
          this,
          Invocation.method(
            #deleteAll,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failures, void>>);
}
