// Mocks generated by Mockito 5.4.4 from annotations
// in cinema_club/test/features/moviesearch/data/repositories/movie_search_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cinema_club/core/network/network_info.dart' as _i2;
import 'package:cinema_club/features/geners/domain/entities/genresEntities.dart'
    as _i6;
import 'package:cinema_club/features/moivesearch/data/datasources/movie_search_remote_data_source.dart'
    as _i4;
import 'package:cinema_club/features/moivesearch/data/models/movie_search_model.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i2.NetworkInfo {
  @override
  _i3.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}

/// A class which mocks [MovieSearchRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieSearchRemoteDataSource extends _i1.Mock
    implements _i4.MovieSearchRemoteDataSource {
  @override
  _i3.Future<List<_i5.MovieSearchModel>> movieSearch(
    String? query,
    List<_i6.GenresEntities>? genres,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #movieSearch,
          [
            query,
            genres,
          ],
        ),
        returnValue: _i3.Future<List<_i5.MovieSearchModel>>.value(
            <_i5.MovieSearchModel>[]),
        returnValueForMissingStub: _i3.Future<List<_i5.MovieSearchModel>>.value(
            <_i5.MovieSearchModel>[]),
      ) as _i3.Future<List<_i5.MovieSearchModel>>);
}
