// Mocks generated by Mockito 5.4.4 from annotations
// in cinema_club/test/features/setting/domain/usecases/get_setting_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cinema_club/core/errors/failures.dart' as _i5;
import 'package:cinema_club/features/setting/domain/entities/setting_entity.dart'
    as _i6;
import 'package:cinema_club/features/setting/domain/repositories/setting_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SettingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingRepository extends _i1.Mock implements _i3.SettingRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failures, _i6.SettingEntity>> getSetting() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSetting,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failures, _i6.SettingEntity>>.value(
                _FakeEither_0<_i5.Failures, _i6.SettingEntity>(
          this,
          Invocation.method(
            #getSetting,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failures, _i6.SettingEntity>>.value(
                _FakeEither_0<_i5.Failures, _i6.SettingEntity>(
          this,
          Invocation.method(
            #getSetting,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failures, _i6.SettingEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failures, void>> saveSetting(
          _i6.SettingEntity? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSetting,
          [settings],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failures, void>>.value(
            _FakeEither_0<_i5.Failures, void>(
          this,
          Invocation.method(
            #saveSetting,
            [settings],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failures, void>>.value(
                _FakeEither_0<_i5.Failures, void>(
          this,
          Invocation.method(
            #saveSetting,
            [settings],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failures, void>>);
}
