// Mocks generated by Mockito 5.4.4 from annotations
// in cinema_club/test/features/add_movie_favorite/domain/usecases/get_favorite_movies_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cinema_club/core/errors/failures.dart' as _i5;
import 'package:cinema_club/features/add_movie_favorite/data/models/movie_favorite_model.dart'
    as _i7;
import 'package:cinema_club/features/add_movie_favorite/domain/repositories/movie_favorite_repository.dart'
    as _i3;
import 'package:cinema_club/features/moviedetails/domain/entities/movie_details_Entity.dart'
    as _i6;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MovieFavoriteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieFavoriteRepository extends _i1.Mock
    implements _i3.MovieFavoriteRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failures, void>> addMovieToFavorite(
          _i6.MovieDetailsEntity? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMovieToFavorite,
          [movie],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failures, void>>.value(
            _FakeEither_0<_i5.Failures, void>(
          this,
          Invocation.method(
            #addMovieToFavorite,
            [movie],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failures, void>>.value(
                _FakeEither_0<_i5.Failures, void>(
          this,
          Invocation.method(
            #addMovieToFavorite,
            [movie],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failures, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failures, void>> deleteMovieFromFavorite(
          int? movieId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMovieFromFavorite,
          [movieId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failures, void>>.value(
            _FakeEither_0<_i5.Failures, void>(
          this,
          Invocation.method(
            #deleteMovieFromFavorite,
            [movieId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failures, void>>.value(
                _FakeEither_0<_i5.Failures, void>(
          this,
          Invocation.method(
            #deleteMovieFromFavorite,
            [movieId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failures, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failures, List<_i7.MovieFavoriteModel>>>
      getFavoriteMovies() => (super.noSuchMethod(
            Invocation.method(
              #getFavoriteMovies,
              [],
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failures, List<_i7.MovieFavoriteModel>>>.value(
                _FakeEither_0<_i5.Failures, List<_i7.MovieFavoriteModel>>(
              this,
              Invocation.method(
                #getFavoriteMovies,
                [],
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                    _i2
                    .Either<_i5.Failures, List<_i7.MovieFavoriteModel>>>.value(
                _FakeEither_0<_i5.Failures, List<_i7.MovieFavoriteModel>>(
              this,
              Invocation.method(
                #getFavoriteMovies,
                [],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failures, List<_i7.MovieFavoriteModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failures, void>> addRemoteMovieToFavorite(
          _i6.MovieDetailsEntity? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRemoteMovieToFavorite,
          [movie],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failures, void>>.value(
            _FakeEither_0<_i5.Failures, void>(
          this,
          Invocation.method(
            #addRemoteMovieToFavorite,
            [movie],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failures, void>>.value(
                _FakeEither_0<_i5.Failures, void>(
          this,
          Invocation.method(
            #addRemoteMovieToFavorite,
            [movie],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failures, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failures, void>> deleteRemoteMovieFromFavorite(
          int? movieId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRemoteMovieFromFavorite,
          [movieId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failures, void>>.value(
            _FakeEither_0<_i5.Failures, void>(
          this,
          Invocation.method(
            #deleteRemoteMovieFromFavorite,
            [movieId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failures, void>>.value(
                _FakeEither_0<_i5.Failures, void>(
          this,
          Invocation.method(
            #deleteRemoteMovieFromFavorite,
            [movieId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failures, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failures, List<_i7.MovieFavoriteModel>>>
      getRemoteFavoriteMovies() => (super.noSuchMethod(
            Invocation.method(
              #getRemoteFavoriteMovies,
              [],
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failures, List<_i7.MovieFavoriteModel>>>.value(
                _FakeEither_0<_i5.Failures, List<_i7.MovieFavoriteModel>>(
              this,
              Invocation.method(
                #getRemoteFavoriteMovies,
                [],
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                    _i2
                    .Either<_i5.Failures, List<_i7.MovieFavoriteModel>>>.value(
                _FakeEither_0<_i5.Failures, List<_i7.MovieFavoriteModel>>(
              this,
              Invocation.method(
                #getRemoteFavoriteMovies,
                [],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failures, List<_i7.MovieFavoriteModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failures, void>> deleteAll() => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failures, void>>.value(
            _FakeEither_0<_i5.Failures, void>(
          this,
          Invocation.method(
            #deleteAll,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failures, void>>.value(
                _FakeEither_0<_i5.Failures, void>(
          this,
          Invocation.method(
            #deleteAll,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failures, void>>);
}
