// Mocks generated by Mockito 5.4.4 from annotations
// in cinema_club/test/features/moviedetails/data/repositories/movie_details_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cinema_club/core/network/network_info.dart' as _i3;
import 'package:cinema_club/features/moviedetails/data/datasources/movie_details_remote_data_source.dart'
    as _i5;
import 'package:cinema_club/features/moviedetails/data/models/movie_details_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMovieDetailsModel_0 extends _i1.SmartFake
    implements _i2.MovieDetailsModel {
  _FakeMovieDetailsModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i3.NetworkInfo {
  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [MovieDetailsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieDetailsRemoteDataSource extends _i1.Mock
    implements _i5.MovieDetailsRemoteDataSource {
  @override
  _i4.Future<_i2.MovieDetailsModel> movieDetailsById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #movieDetailsById,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.MovieDetailsModel>.value(_FakeMovieDetailsModel_0(
          this,
          Invocation.method(
            #movieDetailsById,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MovieDetailsModel>.value(_FakeMovieDetailsModel_0(
          this,
          Invocation.method(
            #movieDetailsById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.MovieDetailsModel>);
}
